//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YchPr_KornilovaVaravra320.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academicians
    {
        public int ID_academicians { get; set; }
        public string FIO { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Specialization { get; set; }
        public Nullable<int> Year_of_assignment { get; set; }
    }
}
