//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YchPr_KornilovaVaravra320.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int ID_ex { get; set; }
        public Nullable<System.DateTime> Date_e { get; set; }
        public Nullable<int> ID_d { get; set; }
        public int Reg_num { get; set; }
        public Nullable<int> Num_emp { get; set; }
        public string Сlassroom { get; set; }
        public Nullable<int> Grade { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Student Student { get; set; }
    }
}
