//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YchPr_KornilovaVaravra320.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Head
    {
        public int Num_emp { get; set; }
        public Nullable<int> Experience { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
