//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YchPr_KornilovaVaravra320.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighSchoolStudents
    {
        public int ID_ss { get; set; }
        public string Name_ss { get; set; }
        public string Item_ss { get; set; }
        public string School_ss { get; set; }
        public Nullable<double> Mark_ss { get; set; }
    }
}
