//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YchPr_KornilovaVaravra320.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YchebnPraktika_Kornilova320Entities : DbContext
    {
        public YchebnPraktika_Kornilova320Entities()
            : base("name=YchebnPraktika_Kornilova320Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academicians> Academicians { get; set; }
        public virtual DbSet<Animals_Kornilova> Animals_Kornilova { get; set; }
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<Control_Kornilova> Control_Kornilova { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<COUNTRY_Kornilova> COUNTRY_Kornilova { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Discipline> Discipline { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Engineer> Engineer { get; set; }
        public virtual DbSet<Exam> Exam { get; set; }
        public virtual DbSet<Faculty> Faculty { get; set; }
        public virtual DbSet<Flowers_Kornilova> Flowers_Kornilova { get; set; }
        public virtual DbSet<Head> Head { get; set; }
        public virtual DbSet<SchoolStudents> SchoolStudents { get; set; }
        public virtual DbSet<Speciality> Speciality { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<HighSchoolStudents> HighSchoolStudents { get; set; }
    }
}
